### ISSUE TITLE
Reduzir cobertura L0 para 16 células

### ISSUE THREAD

**Issue by ppKrauss** [osm-codes/BR#1]
Alguns elementos da porção insular podem ser recodificados sem perda de generalidade. **No final a nova grade, em hexadecimal, terá as ilhas nos geocódigos  FB, FC, F8, F9, FG, FH.** Dessa forma tanto base32 como base16h terão apenas um dígito em *L0*.

![image](https://user-images.githubusercontent.com/1651447/180656955-825518a3-804f-4cfc-8d51-17cdf6826fe0.png)

**Comment by 0e1** [comment]
A estratégia pode ser a seguinte, para recodificar as céluals 4 e F em K:

- Manter 18 células na tabela de cobertura L0;
- Usar K como código das células que cobrem as ilhas;
- Criar lista com as subcélulas da respectiva L0 que são utilizadas numa L0 irmã;
- Garantir que a lista não tenha nenhuma subcélula que se repita nas L0 irmãs;
- Gerar geometria da célula L0 removendo as subcélulas usadas pelas irmãs.

Observação:
- Ao invés de ser K o último digito, podemos reordenar e usar H como sendo o último.

**Comment by 0e1** [comment]
Fiz os ajuste no código em https://github.com/osm-codes/CO_new/commit/cc5a65961f9ea6c7252a63b33f0db7fda706b55b.

Ajustei a interface em https://github.com/osm-codes/WS/commit/6bc7c8efcd0a4d4129c9eb5debaafe12b7a64fbe.

Correções em coberturas brasileiras após reordenação: https://github.com/osm-codes/CO_new/commit/9e6be61b79806f3fb56ab81ed4848032d91e1a62.

A seguir os prefixos usados por região/base:
Rio Grande do Sul: base32: HP,HR,HN,HQ, base16H: FAH, FAG,FBH, FBG;
Ilhas ao sul: base32: H8,H9 base 16h: F4H, F5G;
Ilhas ao norte: base32: HH,HG, base16h: F7H, F7G;

**Comment by ppKrauss** [comment]
Fechando, mas ficou um bug que talvez nada haver com isso, conferir uso de projeção se correta.

![image](https://user-images.githubusercontent.com/1651447/182002392-26c73f7e-55fa-409d-97bc-333c3f22e576.png)

**Comment by 0e1** [comment]
Esse problema está correndo entre células adjacentes.
Por exemplo, http://osm.codes/co~J,QP,QR,QX,QZ, possui um intersecção da ordem de 50 metros entre a célula `J` e as células `Q`.
Notar que o vértice superior esquerdo da célula `QP`e o vértice superior direito da célula `QZ` batem com os vértices inferior esquerdo e direito, respectivamente, da célula `J`. São os vértices intermediários das células `Q`que não estão sobre o lado inferior da célula `J`.

Ainda não consegui identificar a origem do problema. Já descartei a quantidade de dígitos usados na função ST_AsGeoJSONb como fonte do problema. Aumento na quantidade de dígitos, não reduziu a ordem de grandeza da intersecção das células.

**Comment by 0e1** [comment]
> Fechando, mas ficou um bug que talvez nada haver com isso, conferir uso de projeção se correta.

Ver https://github.com/osm-codes/BR_new/issues/2.

**Comment by 0e1** [comment]
> Fechando, mas ficou um bug que talvez nada haver com isso, conferir uso de projeção se correta.
> 
> ![image](https://user-images.githubusercontent.com/1651447/182002392-26c73f7e-55fa-409d-97bc-333c3f22e576.png)

Ver https://github.com/osm-codes/GGeohash/issues/2
